# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd2a0e3476c9a1bac293798bcc49b6552060d6bb249bdfacece640dfebaed07582e8921f675633fe146fcc693bc96d8ea42258ab2bedb421ee60a0e98a9e6d2f

test:
  secret_key_base: 3cceb9d602b4b715a45a6f6debf3b1d1d5a34cce3dc4ebe08bbf0f5643d6a71c01540125f6d278d067880cd83f9a9a7f2997afc4d0d59565ce452f30e0fc9953

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
